### ISSUE TITLE
`enrollmentManager.mdmEnrolledAccountIdWithCompletion` callback is not called on MDM enrolled devices

### ISSUE THREAD

**Issue by rahuljiresal** [microsoftconnect/ms-intune-app-sdk-ios#442]
**Describe the bug:**
Even on MDM enrolled devices, `enrollmentManager.mdmEnrolledAccountIdWithCompletion` is never called back. Are there scenarios where this is expected? 

**To Reproduce**
1. `enrollmentManager.mdmEnrolledAccountIdWithCompletion` callback is never called, which makes me believe that MDM enrollment status of the device is incorrect. 
2. `enrollmentManager.mdmEnrolledAccountId`  returns `nil` for MDM enrolled devices

**Expected behavior:**
`enrollmentManager.mdmEnrolledAccountIdWithCompletion` callback should be called with account id 

**Screenshots and logs:**
- n/a

**Smartphone (please complete the following information):**
- this is happening on all iOS devices for us

**Intune App SDK for iOS (please complete the following information):**
-  Latest version of Intune SDK
- App is native platform
- No errors during or post build

**Additional context:**
Another data point to reproduce
1. Device is MDM enrolled
3. In MAM's APP, "App PIN when device PIN is set" is set to "Not required"
4. App still requires PIN — this means app isn't aware of MDM enrollment status (or status is incorrect)

Is there anything we might be missing that is resulting in MDM enrollment status being incorrect, or the callback not being called? 

In case this is not a bug in the SDK (but something on our end), any help is appreciated.

**Comment by wangxiaoms** [comment]
Hi @rahuljiresal Could you verify that using the latest SDK version. The issue of mdmEnrolledAccountIdWithCompletion never invoking the completion handler is an issue that we fixed in version 19.3.1: https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/tag/19.3.1

The above issue would only happen when the SDK could not detect a MDM enrolled account, which seems to be confirming when you mention that the synchronous mdmEnrolledAccountId API is returning nil. If this is happening when the device is indeed managed, there could be two potential causes:
1.) The app may not be pinned to the device management profile. This can be checked by inspecting management profile in the iOS settings app and ensuring that their app is listed.
2.) You may not have configured IntuneMAMUPN and IntuneMAMOID so unable to determine who the device-enrolled identity is: https://learn.microsoft.com/mem/intune/apps/app-protection-policies#device-management-types
