### ISSUE TITLE
How to get the UPN of the current enrolled account?

### ISSUE THREAD

**Issue by dickverweij** [microsoftconnect/ms-intune-app-sdk-ios#496]
In previous versions we could query the current enrolled UPN. Why is this deprecated? 

We now only can query the entra id (oid) How can we get the upn of the user also?

From the older version:
```

/**
 *  Returns the UPN of the currently enrolled user.  Returns
 *  nil if the application is not currently enrolled.
 *  Should be called only by applications which don't support multiple managed accounts.
 *
 *  @return UPN of the enrolled account
 */
- (NSString *_Nullable)enrolledAccount DEPRECATED_MSG_ATTRIBUTE("Use enrolledAccountId instead.");
```

**Comment by pmod2** [comment]
@dickverweij 
**UserPrincipalName (UPN)** is an attribute that is an Internet-style login name for a user based on the Internet standard RFC 822. It is not a reliable parameter to uniquely identify a user account.

1. It can change overtime.
2. Two completely different accounts can be sharing the same UPN.
3. In order to avoid inconsistencies relating to UPNs, Intune MAM SDK added a set of new APIs that take in Entra ID User ObjectId which is a unique identifier for the user account as a parameter rather than UPN in v16.0.0 (May 2022).

It is strongly recommended that app developers start switching to using the Entra ID User ObjectId based APIs. Any APIs that previously required the app to send in UPN will have a corresponding ObjectID based API. The parameter will be called accountId for all these APIs.
Few examples:

- Use the ObjectId API - `(void)registerAndEnrollAccountId:(NSString *_Nonnull)accountId;` instead of `(void)registerAndEnrollAccount:(NSString *_Nonnull)identity;`
- Use the ObjectId API - `(void)deRegisterAndUnenrollAccountId:(NSString *_Nonnull)accountId withWipe:(BOOL)doWipe;` instead of - `(void)deRegisterAndUnenrollAccount:(NSString *_Nonnull)identity withWipe:(BOOL)doWipe;`
- Use the ObjectId API - `(void) remediateComplianceForAccountId:(NSString*_Nonnull) accountId silent:(BOOL) silent;` instead of - `(void) remediateComplianceForIdentity:(NSString*_Nonnull) identity silent:(BOOL) silent;`

**Comment by pmod2** [comment]
Marking the issue as closed.

**Comment by dickverweij** [comment]
@pmod2 Thanks i will use your reply to suggest to my pears the urge to switch over to entra id !
